### ISSUE TITLE
chuginate failure when Python3 is default

### ISSUE THREAD

**Issue by spencersalazar** [ccrma/chugins#14]
chuginate should either work with Python 2 + Python 3, or fail when attempting to use Python 3. 

From a user:

```
In python3 you get:
python bootstrap.py < chuginate.py > chuginate
Traceback (most recent call last):
  File "bootstrap.py", line 38, in <module>
    b64 = base64.b64encode(f.read())
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
makefile:6: recipe for target 'chuginate' failed
make: *** [chuginate] Error 1

changing the makefile line to be "python2" explicitly helps Make complete, but since chuginate itself is v. 2 I think it causes trouble on systems where 3 is the primary python install.
```

**Comment by spencersalazar** [comment]
fixed it boiiii https://github.com/ccrma/chugins/pull/72
